In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('cust_satisfaction.csv')
df

Gender      Customer Type   Type of Travel     Class  \
0         Male     Loyal Customer  Personal Travel  Eco Plus   
1         Male  disloyal Customer  Business travel  Business   
2       Female     Loyal Customer  Business travel  Business   
3       Female     Loyal Customer  Business travel  Business   
4         Male     Loyal Customer  Business travel  Business   
...        ...                ...              ...       ...   
103899  Female  disloyal Customer  Business travel       Eco   
103900    Male     Loyal Customer  Business travel  Business   
103901    Male  disloyal Customer  Business travel  Business   
103902  Female  disloyal Customer  Business travel       Eco   
103903    Male     Loyal Customer  Business travel  Business   

                   satisfaction  Age  Flight Distance  Inflight entertainment  \
0       neutral or dissatisfied   13              460                       5   
1       neutral or dissatisfied   25              235                       1   
2                     satisfied   26             1142                       5   
3       neutral or dissatisfied   25              562                       2   
4                     satisfied   61              214                       3   
...                         ...  ...              ...                     ...   
103899  neutral or dissatisfied   23              192                       2   
103900                satisfied   49             2347                       5   
103901  neutral or dissatisfied   30             1995                       4   
103902  neutral or dissatisfied   22             1000                       1   
103903  neutral or dissatisfied   27             1723                       1   

        Baggage handling  Cleanliness  Departure Delay in Minutes  \
0                      4            5                          25   
1                      3            1                           1   
2                      4            5                           0   
3                      3            2                          11   
4                      4            3                           0   
...                  ...          ...                         ...   
103899                 4            2                           3   
103900                 5            4                           0   
103901                 4            4                           7   
103902                 1            1                           0   
103903                 4            1                           0   

        Arrival Delay in Minutes  
0                           18.0  
1                            6.0  
2                            0.0  
3                            9.0  
4                            0.0  
...                          ...  
103899                       0.0  
103900                       0.0  
103901                      14.0  
103902                       0.0  
103903                       0.0  

[103904 rows x 12 columns]

In [3]:
df.info() # info of dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103904 entries, 0 to 103903
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   Gender                      103904 non-null  object 
 1   Customer Type               103904 non-null  object 
 2   Type of Travel              103904 non-null  object 
 3   Class                       103904 non-null  object 
 4   satisfaction                103904 non-null  object 
 5   Age                         103904 non-null  int64  
 6   Flight Distance             103904 non-null  int64  
 7   Inflight entertainment      103904 non-null  int64  
 8   Baggage handling            103904 non-null  int64  
 9   Cleanliness                 103904 non-null  int64  
 10  Departure Delay in Minutes  103904 non-null  int64  
 11  Arrival Delay in Minutes    103594 non-null  float64
dtypes: float64(1), int64(6), object(5)
memory usage: 9.5+ MB


In [4]:
df.describe() # info of num data

Age  Flight Distance  Inflight entertainment  \
count  103904.000000    103904.000000           103904.000000   
mean       39.379706      1189.448375                3.358158   
std        15.114964       997.147281                1.332991   
min         7.000000        31.000000                0.000000   
25%        27.000000       414.000000                2.000000   
50%        40.000000       843.000000                4.000000   
75%        51.000000      1743.000000                4.000000   
max        85.000000      4983.000000                5.000000   

       Baggage handling    Cleanliness  Departure Delay in Minutes  \
count     103904.000000  103904.000000               103904.000000   
mean           3.631833       3.286351                   14.815618   
std            1.180903       1.312273                   38.230901   
min            1.000000       0.000000                    0.000000   
25%            3.000000       2.000000                    0.000000   
50%            4.000000       3.000000                    0.000000   
75%            5.000000       4.000000                   12.000000   
max            5.000000       5.000000                 1592.000000   

       Arrival Delay in Minutes  
count             103594.000000  
mean                  15.178678  
std                   38.698682  
min                    0.000000  
25%                    0.000000  
50%                    0.000000  
75%                   13.000000  
max                 1584.000000

In [5]:
df.isnull()   # to check null value 

Gender  Customer Type  Type of Travel  Class  satisfaction    Age  \
0        False          False           False  False         False  False   
1        False          False           False  False         False  False   
2        False          False           False  False         False  False   
3        False          False           False  False         False  False   
4        False          False           False  False         False  False   
...        ...            ...             ...    ...           ...    ...   
103899   False          False           False  False         False  False   
103900   False          False           False  False         False  False   
103901   False          False           False  False         False  False   
103902   False          False           False  False         False  False   
103903   False          False           False  False         False  False   

        Flight Distance  Inflight entertainment  Baggage handling  \
0                 False                   False             False   
1                 False                   False             False   
2                 False                   False             False   
3                 False                   False             False   
4                 False                   False             False   
...                 ...                     ...               ...   
103899            False                   False             False   
103900            False                   False             False   
103901            False                   False             False   
103902            False                   False             False   
103903            False                   False             False   

        Cleanliness  Departure Delay in Minutes  Arrival Delay in Minutes  
0             False                       False                     False  
1             False                       False                     False  
2             False                       False                     False  
3             False                       False                     False  
4             False                       False                     False  
...             ...                         ...                       ...  
103899        False                       False                     False  
103900        False                       False                     False  
103901        False                       False                     False  
103902        False                       False                     False  
103903        False                       False                     False  

[103904 rows x 12 columns]

In [6]:
df.isnull().sum()  # null value in feature

Gender                          0
Customer Type                   0
Type of Travel                  0
Class                           0
satisfaction                    0
Age                             0
Flight Distance                 0
Inflight entertainment          0
Baggage handling                0
Cleanliness                     0
Departure Delay in Minutes      0
Arrival Delay in Minutes      310
dtype: int64

In [7]:
df.dropna(inplace=True) # drop  null value


In [8]:
df.isnull().sum()

Gender                        0
Customer Type                 0
Type of Travel                0
Class                         0
satisfaction                  0
Age                           0
Flight Distance               0
Inflight entertainment        0
Baggage handling              0
Cleanliness                   0
Departure Delay in Minutes    0
Arrival Delay in Minutes      0
dtype: int64

In [9]:
df.duplicated().sum() # to check duplicate value

np.int64(172)

In [10]:
df.drop_duplicates(inplace=True) # drop duplicate value
df.duplicated().sum()

np.int64(0)

unique values of all feature


In [11]:
df.columns

Index(['Gender', 'Customer Type', 'Type of Travel', 'Class', 'satisfaction',
       'Age', 'Flight Distance', 'Inflight entertainment', 'Baggage handling',
       'Cleanliness', 'Departure Delay in Minutes',
       'Arrival Delay in Minutes'],
      dtype='object')

In [12]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [13]:
df['Customer Type'].unique()

array(['Loyal Customer', 'disloyal Customer'], dtype=object)

In [14]:
df['Type of Travel'].unique()

array(['Personal Travel', 'Business travel'], dtype=object)

In [15]:
df['Class'].unique()

array(['Eco Plus', 'Business', 'Eco'], dtype=object)

In [16]:
df['satisfaction'].unique()

array(['neutral or dissatisfied', 'satisfied'], dtype=object)

encoding of cat column

In [17]:
dt={
    'Loyal Customer':1,
    'disloyal Customer':0         # dictonary
    }
#dict_customer_type.keys()
#dict_customer_type.values()
df['Customer Type']=df['Customer Type'].map(dt) # used to map dict and feature
df['Customer Type'].unique()

array([1, 0])

In [18]:
dt1={
    'Male':1,
    'Female':0                    # dictonary
}
df['Gender']=df['Gender'].map(dt1)  # used to map dict and feature
df['Gender'].unique()

array([1, 0])

In [19]:
dt2={
    'Personal Travel':1,
    'Business travel':0             # dictonary
}
df['Type of Travel']=df['Type of Travel'].map(dt2)  # used to map dict and feature
df['Type of Travel'].unique()

array([1, 0])

In [20]:
dt3={
    'Eco Plus':1,
    'Business':0,                # dictonary
    'Eco':2
}
df['Class']=df['Class'].map(dt3)   # used to map dict and feature
df['Class'].unique()

array([1, 0, 2])

In [21]:
dt4={
    'neutral or dissatisfied':1,
    'satisfied':0                             # dictonary
}
df['satisfaction']=df['satisfaction'].map(dt4)  # used to map dict and feature
df['satisfaction'].unique()

array([1, 0])

In [22]:
df.head()

Gender  Customer Type  Type of Travel  Class  satisfaction  Age  \
0       1              1               1      1             1   13   
1       1              0               0      0             1   25   
2       0              1               0      0             0   26   
3       0              1               0      0             1   25   
4       1              1               0      0             0   61   

   Flight Distance  Inflight entertainment  Baggage handling  Cleanliness  \
0              460                       5                 4            5   
1              235                       1                 3            1   
2             1142                       5                 4            5   
3              562                       2                 3            2   
4              214                       3                 4            3   

   Departure Delay in Minutes  Arrival Delay in Minutes  
0                          25                      18.0  
1                           1                       6.0  
2                           0                       0.0  
3                          11                       9.0  
4                           0                       0.0

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 103422 entries, 0 to 103903
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   Gender                      103422 non-null  int64  
 1   Customer Type               103422 non-null  int64  
 2   Type of Travel              103422 non-null  int64  
 3   Class                       103422 non-null  int64  
 4   satisfaction                103422 non-null  int64  
 5   Age                         103422 non-null  int64  
 6   Flight Distance             103422 non-null  int64  
 7   Inflight entertainment      103422 non-null  int64  
 8   Baggage handling            103422 non-null  int64  
 9   Cleanliness                 103422 non-null  int64  
 10  Departure Delay in Minutes  103422 non-null  int64  
 11  Arrival Delay in Minutes    103422 non-null  float64
dtypes: float64(1), int64(11)
memory usage: 10.3 MB


In [24]:
df.describe()

Gender  Customer Type  Type of Travel          Class  \
count  103422.000000  103422.000000   103422.000000  103422.000000   
mean        0.492371       0.817205        0.310292       0.972047   
std         0.499944       0.386500        0.462615       0.962823   
min         0.000000       0.000000        0.000000       0.000000   
25%         0.000000       1.000000        0.000000       0.000000   
50%         0.000000       1.000000        0.000000       1.000000   
75%         1.000000       1.000000        1.000000       2.000000   
max         1.000000       1.000000        1.000000       2.000000   

        satisfaction            Age  Flight Distance  Inflight entertainment  \
count  103422.000000  103422.000000    103422.000000           103422.000000   
mean        0.566959      39.377057      1189.611707                3.357583   
std         0.495499      15.115713       997.510488                1.333102   
min         0.000000       7.000000        31.000000                0.000000   
25%         0.000000      27.000000       414.000000                2.000000   
50%         1.000000      40.000000       843.000000                4.000000   
75%         1.000000      51.000000      1744.000000                4.000000   
max         1.000000      85.000000      4983.000000                5.000000   

       Baggage handling    Cleanliness  Departure Delay in Minutes  \
count     103422.000000  103422.000000               103422.000000   
mean           3.630649       3.285926                   14.772447   
std            1.181313       1.312334                   38.143678   
min            1.000000       0.000000                    0.000000   
25%            3.000000       2.000000                    0.000000   
50%            4.000000       3.000000                    0.000000   
75%            5.000000       4.000000                   12.000000   
max            5.000000       5.000000                 1592.000000   

       Arrival Delay in Minutes  
count             103422.000000  
mean                  15.203922  
std                   38.725894  
min                    0.000000  
25%                    0.000000  
50%                    0.000000  
75%                   13.000000  
max                 1584.000000

In [25]:
df.duplicated().sum()

np.int64(0)

split the data

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
x=df.drop(['Customer Type'],axis=1)
x

Gender  Type of Travel  Class  satisfaction  Age  Flight Distance  \
0            1               1      1             1   13              460   
1            1               0      0             1   25              235   
2            0               0      0             0   26             1142   
3            0               0      0             1   25              562   
4            1               0      0             0   61              214   
...        ...             ...    ...           ...  ...              ...   
103899       0               0      2             1   23              192   
103900       1               0      0             0   49             2347   
103901       1               0      0             1   30             1995   
103902       0               0      2             1   22             1000   
103903       1               0      0             1   27             1723   

        Inflight entertainment  Baggage handling  Cleanliness  \
0                            5                 4            5   
1                            1                 3            1   
2                            5                 4            5   
3                            2                 3            2   
4                            3                 4            3   
...                        ...               ...          ...   
103899                       2                 4            2   
103900                       5                 5            4   
103901                       4                 4            4   
103902                       1                 1            1   
103903                       1                 4            1   

        Departure Delay in Minutes  Arrival Delay in Minutes  
0                               25                      18.0  
1                                1                       6.0  
2                                0                       0.0  
3                               11                       9.0  
4                                0                       0.0  
...                            ...                       ...  
103899                           3                       0.0  
103900                           0                       0.0  
103901                           7                      14.0  
103902                           0                       0.0  
103903                           0                       0.0  

[103422 rows x 11 columns]

In [28]:
y=df['Customer Type']
y

0         1
1         0
2         1
3         1
4         1
         ..
103899    0
103900    1
103901    0
103902    0
103903    1
Name: Customer Type, Length: 103422, dtype: int64

In [29]:
df.duplicated().sum()

np.int64(0)

In [30]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [31]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((82737, 11), (20685, 11), (82737,), (20685,))